spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quickProducts?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: QuickBuy-Products

springdoc:
  packagesToScan: com.QBproducts.QuickBuy_Products.controllers
  pathsToMatch: /product/**